"""phase5_purchases

Revision ID: 53b80a61b462
Revises: 618141e2777f
Create Date: 2026-08-12 06:56:50.294920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b80a61b462'
down_revision: Union[str, None] = '618141e2777f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tin', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('is_vat_registered', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_bills',
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('bill_number', sa.String(length=50), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('journal_entry_id', sa.String(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('input_vat_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('withholding_tax_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_due_to_vendor', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_bill_lines',
    sa.Column('bill_id', sa.String(), nullable=False),
    sa.Column('expense_account_id', sa.String(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_rule_code', sa.String(length=50), nullable=True),
    sa.Column('withholding_tax_rule_code', sa.String(length=50), nullable=True),
    sa.Column('line_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('withholding_tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['purchase_bills.id'], ),
    sa.ForeignKeyConstraint(['expense_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('business_settings', sa.Column('ap_account_id', sa.String(), nullable=True))
    op.add_column('business_settings', sa.Column('input_vat_account_id', sa.String(), nullable=True))
    op.add_column('business_settings', sa.Column('withholding_tax_payable_account_id', sa.String(), nullable=True))
    # SQLite can't ALTER a table to add FK constraints directly --
    # batch mode recreates the table under the hood (copy-and-move),
    # same fix as Phase 4's migration for this same table.
    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_business_settings_input_vat_account', 'accounts', ['input_vat_account_id'], ['id']
        )
        batch_op.create_foreign_key(
            'fk_business_settings_withholding_tax_payable_account',
            'accounts',
            ['withholding_tax_payable_account_id'],
            ['id'],
        )
        batch_op.create_foreign_key(
            'fk_business_settings_ap_account', 'accounts', ['ap_account_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_business_settings_ap_account', type_='foreignkey')
        batch_op.drop_constraint('fk_business_settings_withholding_tax_payable_account', type_='foreignkey')
        batch_op.drop_constraint('fk_business_settings_input_vat_account', type_='foreignkey')
        batch_op.drop_column('withholding_tax_payable_account_id')
        batch_op.drop_column('input_vat_account_id')
        batch_op.drop_column('ap_account_id')
    op.drop_table('purchase_bill_lines')
    op.drop_table('purchase_bills')
    op.drop_table('vendors')
    # ### end Alembic commands ###
