"""phase8_inventory

Revision ID: 60df4e1460a5
Revises: 96f2ad795f3f
Create Date: 2026-08-15 08:17:09.811806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60df4e1460a5'
down_revision: Union[str, None] = '96f2ad795f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('inventory_account_id', sa.String(), nullable=False),
    sa.Column('cogs_account_id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('quantity_on_hand', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['cogs_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['inventory_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'sku', name='uq_item_sku_per_business')
    )
    op.create_table('stock_movements',
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_qty_after', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('balance_value_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('purchase_bill_lines', sa.Column('item_id', sa.String(), nullable=True))
    op.add_column('sales_invoice_lines', sa.Column('item_id', sa.String(), nullable=True))
    # SQLite can't ALTER a table to add FK constraints directly --
    # batch mode recreates the table under the hood (copy-and-move),
    # same fix as Phases 4 and 5's migrations.
    with op.batch_alter_table('purchase_bill_lines', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_purchase_bill_lines_item', 'inventory_items', ['item_id'], ['id']
        )
    with op.batch_alter_table('sales_invoice_lines', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_sales_invoice_lines_item', 'inventory_items', ['item_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoice_lines', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sales_invoice_lines_item', type_='foreignkey')
        batch_op.drop_column('item_id')
    with op.batch_alter_table('purchase_bill_lines', schema=None) as batch_op:
        batch_op.drop_constraint('fk_purchase_bill_lines_item', type_='foreignkey')
        batch_op.drop_column('item_id')
    op.drop_table('stock_movements')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
