"""phase4_sales

Revision ID: 618141e2777f
Revises: bb91eebf88a5
Create Date: 2026-08-12 05:29:24.364405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618141e2777f'
down_revision: Union[str, None] = 'bb91eebf88a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tin', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_invoices',
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('journal_entry_id', sa.String(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_invoice_lines',
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('revenue_account_id', sa.String(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_rule_code', sa.String(length=50), nullable=True),
    sa.Column('line_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ),
    sa.ForeignKeyConstraint(['revenue_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('business_settings', sa.Column('ar_account_id', sa.String(), nullable=True))
    op.add_column('business_settings', sa.Column('output_vat_account_id', sa.String(), nullable=True))
    # SQLite can't ALTER a table to add FK constraints directly --
    # batch mode recreates the table under the hood (copy-and-move).
    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_business_settings_output_vat_account', 'accounts', ['output_vat_account_id'], ['id']
        )
        batch_op.create_foreign_key(
            'fk_business_settings_ar_account', 'accounts', ['ar_account_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_business_settings_ar_account', type_='foreignkey')
        batch_op.drop_constraint('fk_business_settings_output_vat_account', type_='foreignkey')
        batch_op.drop_column('output_vat_account_id')
        batch_op.drop_column('ar_account_id')
    op.drop_table('sales_invoice_lines')
    op.drop_table('sales_invoices')
    op.drop_table('customers')
    # ### end Alembic commands ###
