"""phase9_fixed_assets

Revision ID: 76e50e5c8f64
Revises: 60df4e1460a5
Create Date: 2026-08-15 08:22:42.592872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e50e5c8f64'
down_revision: Union[str, None] = '60df4e1460a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_assets',
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('asset_account_id', sa.String(), nullable=False),
    sa.Column('accumulated_depreciation_account_id', sa.String(), nullable=False),
    sa.Column('depreciation_expense_account_id', sa.String(), nullable=False),
    sa.Column('asset_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('acquisition_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('salvage_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('useful_life_months', sa.Integer(), nullable=False),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accumulated_depreciation_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['asset_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['depreciation_expense_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depreciation_entries',
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('journal_entry_id', sa.String(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('depreciation_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('accumulated_depreciation_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('book_value_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['fixed_assets.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'period_year', 'period_month', name='uq_depreciation_asset_period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('depreciation_entries')
    op.drop_table('fixed_assets')
    # ### end Alembic commands ###
