"""phase3_tax_engine

Revision ID: bb91eebf88a5
Revises: 2fae50917d25
Create Date: 2026-08-11 09:11:43.509458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb91eebf88a5'
down_revision: Union[str, None] = '2fae50917d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_rules',
    sa.Column('business_id', sa.String(), nullable=True),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_type', sa.String(length=20), nullable=False),
    sa.Column('atc_code', sa.String(length=20), nullable=True),
    sa.Column('rate_percent', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('legal_basis', sa.String(length=255), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_rules')
    # ### end Alembic commands ###
